### PR TITLE
added 2016 general election precinct data

### PR DESCRIPTION
**Pull request by crockettcobb**
available from
https://www.ok.gov/elections/Election_Info/2016_November_General_Election.html

this CSV needs a fair amount of cleanup, but I couldn't find an openelections-sources-ok repo. I'm happy to work out the parser to clean up into a grouped-by-county precinct-level parser.

### CODE REVIEW

**Comment by dwillis** [comment]
Hi @crockettcobb: Thanks! We could go two routes:

1. Clean up the CSV you've generated so it roughly fits our usual standard (you could keep multiple vote breakdowns).
2. Create a sources repo and put this file there.

Of the two, I think I prefer the first option if you're up to it.

**Comment by crockettcobb** [comment]
Sure. I'll get cracking on a cleaned up CSV to meet the standards and commit tothis branch.

**Comment by dwillis** [comment]
Thanks!

**Comment by crockettcobb** [comment]
The latest commit on `08a2df4` is my first pass at cleaning it up. I wasn't sure of the exact naming convention for absentee, mail-in, and election day votes.

**Comment by dwillis** [comment]
Looks good, thanks!

**Pull request merged**
